version: '3.1'

services:
  db:
    image: postgres
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_PASSWORD: password

  adminer:
    image: adminer
    container_name: adminer_container2
    restart: always
    ports:
      - 8081:8081