version: '3.1'

services:
  db:
    image: postgres
    container_name: postgres_container
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./example_db:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer_container2
    restart: always
    ports:
      - 8080:8080
volumes:
  example_db: