name: list-s3-buckets

on:
  push:
    branches:
      - main
jobs:
  list-s3-buckets:
    name: List S3 buckets in account
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: eu-west-1
    steps:
      - name: checkout-repo
        uses: actions/checkout@v2
      - name: list-dir
        run: | 
          echo "Homebru!"
          ls
      - name: list-s3
        run: aws s3 ls